# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceitem_taxable_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='taxable_amount',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax applied on this item.', max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(help_text='Customer whom invoice is for.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.Customer'),
        ),
    ]
