# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the customer.', max_length=255)),
                ('address_line_1', models.CharField(help_text='Address line 1 of the customer.', max_length=512)),
                ('address_line_2', models.CharField(help_text='Address line 2 of the customer.', max_length=512)),
                ('state', models.CharField(help_text='State of the customer.', max_length=12)),
                ('phone', models.CharField(help_text='Contact number of the customer.', max_length=12)),
                ('consumer_number', models.CharField(blank=True, help_text='Consumer number of the customer in the company.', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True)),
                ('key', models.CharField(help_text='Key of the extra info.', max_length=30)),
                ('value', models.CharField(help_text='Value of the extra info.', max_length=127)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
