# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerextrainfo',
            unique_together=set([('customer', 'key')]),
        ),
    ]
