# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170715_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Address line 2 of the customer.', max_length=512),
        ),
    ]
