# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_1',
            field=models.ImageField(default='lsknlck', help_text='Primary logo of the company.', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo_2',
            field=models.ImageField(blank=True, help_text='Secondary logo of the company.', null=True, upload_to=b''),
        ),
    ]
