# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True)),
                ('sku', models.CharField(help_text="'Stock Keeping Unit' code of the item.", max_length=30)),
                ('hsn', models.CharField(blank=True, help_text="'Harmonized System of Nomenclature' code of the item.", max_length=60)),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('description', models.TextField(help_text='Description of the item.')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock of the item.')),
                ('tax_notes', models.CharField(blank=True, help_text='Notes about the tax applied on the item.', max_length=60)),
                ('company', models.ForeignKey(help_text='Company to which item belongs', on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
