# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('company', 'sku')]),
        ),
    ]
