# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, help_text="'Harmonized System of Nomenclature' code of the item.", max_length=60, verbose_name='HSN'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(help_text="'Stock Keeping Unit' code of the item.", max_length=30, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax_notes',
            field=models.CharField(blank=True, help_text='Notes about the tax applied on the item.', max_length=60, verbose_name='Tax Notes'),
        ),
    ]
